window.HOROSCOPES = {
  "Aries": [
    "You’ll soon contribute a poetic insight in a class discussion that will make your professor internally scream.",
    "Always put your best foot forward, Aries. Leave that infected other foot behind, you warty weirdo.",
    "During your astrological month, try to upgrade the amount of service projects you are doing for those around you. The occasional “putting up the toilet seat before you pee” just isn’t cutting it for the karmic forces anymore.",
    "Today is the first day of the rest of your life, Aries. Fascinatingly, today is also the last day of the rest of your life. Go figure!",
    "While most advise to \"trust your gut,\" in your case, maybe think twice before trusting an organ independently-powered by Caramel Ribbon Crunch Frappuccinos.",
    "In the coming weeks, expect a complete and total American identity crisis when you realize that you have started to care about your fellow man and feel not only the pains of your own disadvantages but those of the lesser-privileged as well.",
    "When it’s all said and done, you’ll realize that you were alone the whole time. Aside from your imaginary friend, who just wishes you would speak to them one more time.",
    "Patience is key, Aries! However, when patience doesn’t work, just sleep for as long as you can every day to avoid the delusion-filled pandemonium that is your waking life.",
    "You often find comfort in the loving embrace of family. Your family does, however, burn their clothing and hose themselves off with isopropyl after your visits.",
    "Although it may not feel like it, someday you will recount this part of your life as \"where it all went wrong”.",
    "Few other signs have the wild curiosity of the Aries. Even fewer share your intense obsession with horrific footage of car accidents.",
    "Start training your imagination now, Aries! There will soon be a time where you will need to imagine yourself anywhere other than an emergency room!",
    "Gone are the days of meaningless, failed romances! Now begin the days of highly-destructive-to-your-emotional-wellbeing failed romances."
  ],
  "Taurus": [
    "This week, you will set a world record for the number of times a human’s fingers can be slammed in a car door.",
    "Your generosity will shine this week when you decide to let the hostages have a few bottles of Powerade instead of making them drink from the ceiling leak.",
    "You never did like it when people told you what to do. Good on you for never following those pesky Biohazard Isolation Area signs.",
    "Paper cuts don’t normally require medical attention. But, paper cuts don’t usually come from small, nocturnal goblins that carry around pieces of paper with the sole mission of spreading their syphilis, like the one you got last week.",
    "You’ll be surrounded by laughter this week. Interestingly enough, that laughter will promptly cease once you eventually put on underpants.",
    "You refuse to conform to your family’s ideas of right and wrong, which is exactly what you tell yourself right after you walk out of the bathroom without flushing.",
    "You’re not the kind of person who jumps on a bandwagon. Unfortunately, no one else is either and the bandwagon is now without a driver, hurtling towards a playground.",
    "Gone are the days of melancholic moping in your bedroom. You’ll soon find even better places to spread your hatred of life, like the grocery store or senior center cafeteria!",
    "Your legacy won't be defined by your net worth, job title, or charitable deeds. Instead, it will most likely be that one time you fell down the stairs in front of your entire 8th grade class.",
    "Forgive and forget, Taurus. Forget so hard that it infiltrates your dreams, allowing unresolved aggression to reign supreme over your subconscious.",
    "Betrayal is your least favorite feeling, Taurus. This will become especially frustrating when your bowels do just that later this evening."
  ],
  "Gemini": [
    "Trying to remain politically optimistic, Gemini? Well, the stars will just go fuck themselves then.",
    "Your gullibility shocks even the least sophisticated of people. Also, if you look on the back of this issue, there is a special message to you from God himself.",
    "As your friendships wither into jealousy-riddled husks of their former selves, know that the way to win your pals back is by offering endless critique on how they can improve.",
    "The stars sense that your stress levels are on the rise. This can directly be resolved by drilling a large, nickel-sized hole directly into your forehead. Or drugs.",
    "The most desirable people are often those who are the furthest from your grasp, Gemini. Jimmy Carter will never want you, and that’s a reality you must face.",
    "No one around you knows how sophisticated and cultured you really are. Obnoxiously remind them at every single opportunity.",
    "You now represent the hopes and dreams of all former versions of yourself, which is especially interesting considering that most of your prior selves have been entirely uninteresting and generally worthless.",
    "You will persevere until you get what you deserve, Gemini – as long as what you deserve isn’t all that difficult to achieve and doesn’t interfere with your rigid schedule of rotting in your bed for days at a time.",
    "Some can live while others thrive, Gemini. The difference usually lies between those who know of the Big Mac and those who understand the Big Mac.",
    "There are few that understand your genius, Gemini. This is probably because your “genius” involves finger paints and a lot of screaming.",
    "Sport has never seemed to impress the Gemini. You instead seem to find greater spectacle in watching the lives of others burn.",
    "Your family’s collective value of “sticking up for yourself” will finally flourish within you when your grandmother makes fun of your love life and you beat the shit out of her."
  ],
  "Cancer": [
    "You are a healthy, attractive young person with an active social life. Unfortunately, your lust for manipulative narcissists will soon be too strong to resist, leading you straight into marriage.",
    "Slacking off at work might feel nice now, but it will affect more than just you in the future. People really need pediatric surgeons to know what they're doing.",
    "After longing for community for so long, you will soon find your tribe in what its members call the “buttcheek amputees anonymous” club.",
    "It is unlikely that your hideously-lopsided face will attract a future partner, but good on you for fighting the good fight.",
    "You’ve always hated clichés and overused jokes, which is especially ironic due to the fact that you will die by a falling piano.",
    "You seem to be drawn to the parts of our culture that offer clarity about the human condition. Paradoxically, you still seem to be confused in some of the very fundamental areas being human, like urinating in the appropriate room.",
    "The next month of your life will perhaps be the most interesting yet, Cancer. So interesting, in fact, that far fewer will end up at your funeral than originally invited.",
    "The stars announce, after much deliberation, that you will spontaneously combust sometime within the next 40 years.",
    "Although you've shaken hands with hundreds of people in your lifetime, you still find new and improved ways to make it miserable for each new person you meet.",
    "For many, spring is a time of rebirth. For you, the feeling of rebirth is produced through watching your hometown swallowed by a gorgeous blaze.",
    "Accurate to your sign, those in your life often view you as a sort of uncontrollable disease that can only be removed through extensive exposure to radiation.",
    "You refuse to buy-in to society’s idea of “failure”. You’d rather consider yourself “the world’s leading Top Ramen researcher”."
  ],
  "Leo": [
    "Nothing even remotely noteworthy will happen to you this week, but the stars guarantee you’ll call your parents and bore them even closer to death telling them about it.",
    "Changing directions in life isn’t as scary as it sounds! Also, you missed the turn three exits ago.",
    "The holidays can be difficult, Leo. This year, bypass the yuletide melancholy by just freezing to death.",
    "Much like the fable of The Little Red Hen, you’re sure to become a passive aggressive cock that won’t share your delicious bread.",
    "Although everyone in the world may disagree, the stars still claim that you are typically known as “likable” and “not horrific.”",
    "A real friend is one that will stand up for you in difficult situations. Let your friends know that their support doesn’t go unnoticed by saying, “I want to bear your child.”",
    "You’ve always believed that happiness is not a destination but a practice, Leo. However, the stars can assure you that you have no idea what you are talking about and should shut up with all that hippy-dippy bullcrap.",
    "Long after you’re gone, people will remember you for your strength, bravery, and dedication to falsifying your entire personality.",
    "Leaning on childhood comforts is totally acceptable every now and then. However, your friends might feel betrayed if you keep having lunch with your stuffed animals instead of them.",
    "Let loose this month, Leo! The stars stopped caring about you a long time ago and could care less about your actions!",
    "Although you’ve never felt greater inner-peace, this is likely because of the three hours you’ve spent fighting for your life on the toilet today.",
    "Years after the whole “killer clowns” trend died off, you’ll find it quite strange when 30 of them flood into your room later tonight."
  ],
  "Virgo": [
    "Doodling in class is often a sign of high creativity, intelligence, or, in your case, a terrifying fascination with what your instructor’s toes may look like.",
    "The Virgo sign is named after Demeter, the Greek goddess of the harvest. Your astrological namesake would be so proud of the mold growing on the blueberry bagels you haven’t touched in three weeks.",
    "It’s about time that you consider yourself a human being, Virgo. Human beings are worth good money these days.",
    "Keep your friends close and your enemies closer, Virgo. In fact, keep everyone so close that the line between friend and foe blurs, creating a tangled web of trust and betrayal where no one–least of all you–can tell where the knife will fall next.",
    "You have always pined for a simple life, free of the consequences of your overwhelming narcissism.",
    "It seems that you’ve plateaued in terms of emotional maturity. Not to worry! You’re soon to join your entire family in the halls of humanity’s least tolerable!",
    "You’ve always been hesitant to acknowledge the existence of a higher power and that’s okay; the higher power normally ignores your existence, too.",
    "Your soul yearns for deeper purpose, Virgo. This would be quite helpful if your mind wasn’t so bent on exemplifying mediocrity.",
    "Although you never learned how to fix a flat tire, you're sure you'll learn how before your spouse and children's lives utterly depend on it.",
    "Don’t be fooled by the prideful man, Virgo. Instead, be fooled by the silly man with a crooked smile and a bone to pick.",
    "The things we love often inspire our behaviors, Virgo. Burger King, chewing tobacco, and sleeping instead of facing problems are clearly very important to you.",
    "Never worry about the parts of your life that you have no control over, Virgo. Worry about the things you do have control over, such as the starving man you captured in your basement."
  ],
  "Libra": [
    "A momentary confusion about your stove’s LOW/HI orientation will bring you closer to death than you’ve ever been.",
    "Turns out you’ll never get that Mercedes, Libra, which is totally all right considering that you’ll go blind in a few weeks anyway.",
    "Stop crying over spilt milk and start crying about real things like your ruinous addiction to Oxycontin.",
    "What is at the bottom of the ocean? What do sunken pirate ships look like? How quickly does a human being sink when a cinder block is chained to all four of its limbs? You’ll learn the answers to all of these questions very soon!",
    "Don’t sweat the small stuff today! Instead, sweat the big stuff, like your devastating addiction to whippets.",
    "You still haven’t found the one, Libra, which means that this so-called “witch” has a lot of explaining to do about her so-called “lovey-dovey-heartthrob-tonic.”",
    "Although you seem quiet and reserved at work, no one knows that on the inside, you are entirely dead and a sickly blackness has enveloped your soul.",
    "Vigorously pursue your passions to deepen your understanding of your inner self, Libra. Or don’t, and continue your zealous fascination with mediocrity.",
    "Nothing entertains the curious Libra more than thinking about the rudimentary problems within society, religion and the personalities of your closest friends.",
    "There's nothing quite like a warm bath and a cigarette after a long day of worrying about your problems instead of fixing them.",
    "Venus smiles upon you this month, Libra. Unfortunately, due to everything going on with your life, you are unable to smile back.",
    "Despite everything that will happen this evening, walking away with at least one of your arms will be a significant triumph.",
    "Let your inner good samaritan shine through today! You’ll need to start somewhere if you ever want to be loved again."
  ],
  "Scorpio": [
    "Your raging cynicism will soon prove useful when you realize that seeing the worst in life comes with no real consequences.",
    "Unsurprisingly, your long-established negative habits won’t magically disappear this month. Better luck next month.",
    "You are really talented when it comes to killing two birds with one stone. Unfortunately, those birds were mating bald eagles and now you face 10 years in federal prison and a $500,000 fine for felony convictions.",
    "Cut yourself some slack this week, Scorpio. How were you supposed to know what a savings account even is?",
    "Today’s energy lights a fire underneath your ambitions, Scorpio. Unfortunately, that same fire will soon spread to your insecurities, creating a gorgeous blaze of raging delusion!",
    "Growing up, you didn’t care what you did for a job as long as you were good at it. Years later, no one had any idea someone could be this good at being undesirable, much less make a living off of it.",
    "Remember, Scorpio, relationships are either growing or dying. Remarkably, your relationships seem to be doing neither, signaling the fading relevance of your being to the world!",
    "Avoid overidentifying with your emotions this month, Scorpio. Instead, overidentify with things less volatile, like your disgusting face.",
    "Your recurring nightmares announce their plan to merge into one, horrifying visual of a bloodthirsty panther hunting you as your third grade bully yells, “you never belonged on the tire swing!”",
    "Although your recurring fear of being annoying usually feels irrational, your loved ones can confirm that you're just as bothersome as you fear you are.",
    "Stay focused and don’t give up, O Scorpio! But, if you do give up, the stars can assure that you probably wouldn’t have made it very far anyways.",
    "Although nearly everyone in your life has abandoned you and loneliness rules your life, the fleas that inhabit your scalp truly love you and care that you exist.",
    "The stars foresee good fortune in your future. Might as well put $30,000 on black, just to be sure. Lakers +4.5 is also a pretty good idea if you know what I mean.",
    "It seems like nothing in your life is helping with your intense identity crisis, Scorpio."
  ],
  "Sagittarius": [
    "Your life is about to become a permanent euphoric bliss as soon as that check moves from “pending” to “deposited.”",
    "The universe seems to keep kicking you while you’re down. Little does the universe know of your love for foot-biting.",
    "It might be time to break the ice with that person you’ve been interested in. Sneaking into their house and watching them masturbate is getting a little old.",
    "Your calm and relaxed aura does little for the trail of that guy’s blood you’ve been leaving for the last three blocks.",
    "The planet Jupiter dictates that you should not take to the streets with relentless bloodlust– yet!",
    "At this exact moment in time, hundreds of miles away, there is a family sitting around the dinner table laughing as they describe a ridiculous and laughable fictional person. Astoundingly, you are a 98% match of the character they've dreamed up.",
    "You’ve always been in a rush to grow up, which is terrifying considering that your maturation is a necessary checkpoint in the downfall of our entire species.",
    "The wanderlust of the Sagittarius will propel you past the limits of many others. Unfortunately, you will eventually wander so far that no one will be able to hear the sounds of your bones being crunched up by starved orangutans.",
    "Sagittarius, you've never felt more connected to Mother Nature, yet you've never defecated in ponds so frequently.",
    "After 20 long years of sharpening your charisma and polishing your social skills, you can finally hold a conversation with your barber for about half of a haircut.",
    "Your impulsive nature will lead you to make some questionable decisions this month. Don't worry, your regret will only last a lifetime.",
    "The days of budgeting and worrying about money are long-gone! The only currency that is used in the place you’re headed is cigarettes and postage stamps!",
    "You’re the type to open yourself up to new experiences, but only if they involve gambling."
  ],
  "Capricorn": [
    "Friday afternoon will leave you lost and alone in a life you shouldn’t have chosen. Try to ignore that feeling until you get back to the office on Monday.",
    "You’ve never tripped as many deadly booby traps as you will tomorrow.",
    "You always say that there is a method to your madness. However, your family is still waiting for you to master the method of shitting while standing up.",
    "Never reveal that you were wrong, Capricorn. Instead, reveal that you were under the influence of a centuries-old llama goddess and it was she, in fact, who forgot to Venmo after the movie.",
    "Although your dedication to charity should grant you a seat in the heavens, due to a small administrative error, your immortal soul will soon be relocated to The Sea of Writhing Flames.",
    "You find that you rush into situations frequently, which is especially frustrating considering that you keep finding yourself matched against wise tortoises.",
    "Scientists agree that you are an incredibly fascinating specimen, but they haven’t found a situation where you could possibly be put to use.",
    "Much of your life is spent worrying about what others think of you. Try and move past this by worrying about other things, like your relationship with barbiturates.",
    "Your obsession with unattainable perfection will once again completely ruin your chances of finding love, enjoying life.",
    "Unfortunately for you and everyone involved, the stars can assure you that tomorrow is going to happen.",
    "Your magnetic charisma will bring you attention from many this month! Unfortunately, most of them are very weird.",
    "True to the dependable nature of the Capricorn, those around you can always rely on you to ruin everything by simply existing.",
    "You may feel yourself getting lost in life. Coincidently, the new 2023 Rand McNally Road Atlas just came out and it is now 25% off for a limited time!"
  ],
  "Aquarius": [
    "The time has come to emotionally deal with your less-than-perfect adolescence. After all, you were the recipient of the local Burger King’s “500,000th Burger Sold” plaque.",
    "The global fashion police will soon be in touch about the illegality of wearing ball caps on watermelon-sized heads.",
    "“A picture is worth 1000 words”, everyone will say to you after the image of your massive naked Barbie collection surfaces.",
    "Before you lie many paths forward, Aquarius. However, only one of these paths lead to a chiropractor going through a divorce. Choose wisely.",
    "Withhold your love from those undeserving, Aquarius. Your mother might be proud of you.",
    "The stars are happy to announce that you have around 12 more years before the wrinkles set in and about 27 before you become so frustrated by your aged visage that you rip your skin off in an ape-like fury.",
    "Many times you find yourself dreaming about walking into your elementary school having forgotten to put on clothes that morning. This is the work of a hypnotherapist finding any possible way for you to forget that this was, in fact, reality.",
    "An election year may have the sensitive Aquarius especially antsy. Rest assured, 2024 will provide you with every motivation to flee to a remote island where elections usually happen every 80 years and involve only slightly less murder.",
    "The saying goes, “if you want something done right, do it yourself.” Paradoxically, when you try to do something yourself, it usually ends up either harming people or disappointing your family.",
    "There's no telling where you'd be if your parents hadn't met and instead took vows of celibacy.",
    "As the innovator of the Zodiac, you’ll always find new ways to be annoying as hell to those that you love.",
    "Your hard work is paying off, Aquarius! Burying the bodies of your victims underneath your house is finally producing the smell you hoped for!",
    "Phew, that might have been the worst trip to the dentist’s office. Rest assured, it wasn’t."
  ],
  "Pisces": [
    "No one takes you seriously. Try screaming a little louder.",
    "For being such a boring and uncompelling person, you sure can make a good-looking salad.",
    "*Editor's Note: The horoscope columnist died before he could come up with anything interesting to say about Pisces*",
    "Inside of you is both shadow and light, fire and ice, McDonald’s Hamburger and McDonald’s Chicken Sandwich. It's up to you which side you let out.",
    "After years of adamantly believing otherwise, you'll soon realize you're not, in fact, \"all that and a bag of chips.\"",
    "You continue to find the beings around you entirely wonderful. And yet, everyone you meet seems to look at you with the same tired eyes that silently say, “God, I wish they would just shut up about psychedelics.”",
    "Today is the day that the Lord hath made, let us rejoice and sleep until noon soas to avoid the senseless dystopia that is being awake.",
    "You’ll never again be as happy as you will be this week when neurosurgeons attach electrodes to the appropriate sections of your brain’s pleasure center and simulate the feeling of a loving family.",
    "While you often struggle to connect with strangers, take comfort in the fact that they're often too busy being uninterested in life's bizarre sitcom to notice your quirky character.",
    "While water is the designated element of Pisces, for you, the zodiac suggests a more fitting combination of inexpensive vodka and tears.",
    "The stars are ready for summer and really don’t care about giving Pisces their horoscope. Better luck next year!",
    "Don’t forget to stop and smell the roses every once-in-a-while, Pisces. They probably won’t be around much longer considering the sheer amount of methane gas you release into the ozone layer daily.",
    "For centuries, researchers have been attempting to decipher why humans feel the need to steal the belongings of others. Thanks to you and your efforts, researchers will have an all-encompassing knowledge of this phenomenon."
  ]
};
